### ISSUE TITLE
Do faster typists type letters at positions with less uncertainty faster?

### ISSUE THREAD

**Issue by wlai0611** [CrumpLab/EntropyTyping#4]
I posted Walt'sAnalysis.R in our Code and made a graph of r vs. IKSI each subject being a dot.  
THe r correlates IKSIs with H for each subject.  I am getting a t value of -5.9 for the slope of r Vs. IKSI but am not sure if I am valid in interpreting that there is an effect of expertise on sensitivity to H.

**Comment by CrumpLab** [comment]
Walter, quick question, do you know how to use an .RMD file instead of an .r file? If you use the .RMd file (r markdown) then you can compile your code and it will print out an .html file that you can also upload. This will make everything faster for me to look at. 

Let me know, I can quickly create one for you if you'd like

**Comment by wlai0611** [comment]
Check "Code" I uploaded the rmd and html.

**Comment by CrumpLab** [comment]
Nice, walking in to office, will check in a bit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrumpLab** [comment]
Your analyses looks right to me. Nice work. I'm going to close this issue and split it into a few sub issues. You've done a couple important things here. 1) calculated correlations between mean iksi and H for each subject, 2) calculated average r^2 across subjects, and 3) plotted this against overall mean iksi, which is a decent  measure of expertise. I'm going to create new issues around these three topics, and then we can all write our own code to confirm the numbers.
